on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-targets --verbose
    - name: Tests
      run: cargo test --all --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Format
      run: cargo fmt --all -- --check
